# This is a basic workflow to help you get started with Actions

name: firebase functions deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: create .firebaserc
        run: |
         touch .firebaserc
         echo '{' >> .firebaserc
         echo ' "projects":  {' >> .firebaserc
         echo '  "default": "havit-wesopt29"' >> .firebaserc
         echo ' }' >> .firebaserc
         echo '}' >> .firebaserc
         
      - name: Setting Slack API
        run: |
         touch deployMessageToSlack.sh
         echo 'curl -X POST -H 'Content-type: application/json' --data  "{\"text\":\" [DEPLOY] [HAVIT_SERVER] deployment successful.\", \"icon_emoji\": \":ghost:\"}" ${{ secrets.DEV_WEB_HOOK_ERROR_MONITORING }}' >> deployMessageToSlack.sh
         chmod 755 deployMessageToSlack.sh
         
      - name: create env file
        run: |
          cd functions
          touch .env
          echo "DEV_WEB_HOOK_ERROR_MONITORING=${{ secrets.DEV_WEB_HOOK_ERROR_MONITORING }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DB=${{ secrets.DB_DB }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "TYPE=${{ secrets.TYPE }}" >> .env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
          echo "PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}" >> .env
          echo "CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "AUTH_URI=${{ secrets.AUTH_URI }}" >> .env
          echo "TOKEN_URI=${{ secrets.TOKEN_URI }}" >> .env
          echo "AUTH_PROVIDER_CERT_URL=${{ secrets.AUTH_PROVIDER_CERT_URL }}" >> .env
          echo "CLIENT_CERT_URL=${{ secrets.CLIENT_CERT_URL }}" >> .env
          echo "PUSH_SERVER_URL=${{ secrets.PUSH_SERVER_URL }}" >> .env
          
      - name: Create service account file
        run: |
          cd functions
          touch havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo '{' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "type": ${{ secrets.TYPE }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "project_id": ${{ secrets.PROJECT_ID }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "private_key": ${{ secrets.PRIVATE_KEY }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "private_key_id": ${{ secrets.PRIVATE_KEY_ID }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "client_email": ${{ secrets.CLIENT_EMAIL }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "client_id": ${{ secrets.CLIENT_ID }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "auth_uri": ${{ secrets.AUTH_URI }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "token_uri": ${{ secrets.TOKEN_URI }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "auth_provider_x509_cert_url": ${{ secrets.AUTH_PROVIDER_CERT_URL }}, ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo ' "client_x509_cert_url": ${{ secrets.CLIENT_CERT_URL }} ' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
          echo '}' >> havit-wesopt29-firebase-adminsdk-mgljp-478046b091.json
      
      - name: Install npm pacakges
        run: |
          cd functions
          npm install
          npm install -g firebase-tools
          npm install --save-dev cross-env
      
      - name: Deploy to Firebase
        run: |
          cd functions
          npm run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
